#define WEIGHT1 "../includes/pretrained/weights_layer1.txt"
#define WEIGHT2 "../includes/pretrained/weights_layer2.txt"
#define WEIGHT3 "../includes/pretrained/weights_layer3.txt"
#define WEIGHT4 "../includes/pretrained/weights_layer4.txt"
#define WEIGHT5 "../includes/pretrained/weights_layer5.txt"
#define WEIGHT6 "../includes/pretrained/weights_layer6.txt"
#define WEIGHT7 "../includes/pretrained/weights_layer7.txt"
#define WEIGHT8 "../includes/pretrained/weights_layer8.txt"

#define BIAS1 "../includes/pretrained/biases_layer1.txt"
#define BIAS2 "../includes/pretrained/biases_layer2.txt"
#define BIAS3 "../includes/pretrained/biases_layer3.txt"
#define BIAS4 "../includes/pretrained/biases_layer4.txt"
#define BIAS5 "../includes/pretrained/biases_layer5.txt"
#define BIAS6 "../includes/pretrained/biases_layer6.txt"
#define BIAS7 "../includes/pretrained/biases_layer7.txt"
