#define WEIGHT1 "../pretrained/weights_layer1.txt"
#define WEIGHT2 "../pretrained/weights_layer2.txt"
#define WEIGHT3 "../pretrained/weights_layer3.txt"
#define WEIGHT4 "../pretrained/weights_layer4.txt"
#define WEIGHT5 "../pretrained/weights_layer5.txt"
#define WEIGHT6 "../pretrained/weights_layer6.txt"
#define WEIGHT7 "../pretrained/weights_layer7.txt"
#define WEIGHT8 "../pretrained/weights_layer8.txt"

#define BIAS1 "../pretrained/biases_layer1.txt"
#define BIAS2 "../pretrained/biases_layer2.txt"
#define BIAS3 "../pretrained/biases_layer3.txt"
#define BIAS4 "../pretrained/biases_layer4.txt"
#define BIAS5 "../pretrained/biases_layer5.txt"
#define BIAS6 "../pretrained/biases_layer6.txt"
#define BIAS7 "../pretrained/biases_layer7.txt"
